import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Connect from '../components/Connect'
import { getW3Address, getW3Chain } from 'w3-evm-react'

export default function Home() {
  
  const address = getW3Address()
  const chain = getW3Chain()
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Connect/>
        <br/>
        User: { address }
        <br/>
        Chain: {chain}
      </main>
    </>
  )
}