import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getW3Address, getW3Chain, useConnect } from 'w3-evm-react'
import Connect from '../components/Connect'


export default function Home() {
  
  const { wait } = useConnect()

  const address = getW3Address()

  const chain = getW3Chain()
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        <Connect/>
        <br />
        <br />

        { wait.state ? `${wait.reason}...` : (address ? "Connected" : "Connect Your Wallet") }
        <br/>
        <br/>
        User: { address }
        <br/>
        <br/>
        Chain: {chain}
      </main>
    </>
  )
}